// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed Resources/Sounds/zip.mp3
var resourceZipMp3Data []byte
var resourceZipMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/zip.mp3",
	StaticContent: resourceZipMp3Data,
}

//go:embed Resources/Sounds/wheeHoo.mp3
var resourceWheeHooMp3Data []byte
var resourceWheeHooMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/wheeHoo.mp3",
	StaticContent: resourceWheeHooMp3Data,
}

//go:embed Resources/Sounds/boing.mp3
var resourceBoingMp3Data []byte
var resourceBoingMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/boing.mp3",
	StaticContent: resourceBoingMp3Data,
}

//go:embed Resources/Sounds/uhOh.mp3
var resourceUhOhMp3Data []byte
var resourceUhOhMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/uhOh.mp3",
	StaticContent: resourceUhOhMp3Data,
}

//go:embed Resources/Images/KrankyBearTrapperRedPlaid.png
var resourceKrankyBearTrapperRedPlaidPngData []byte
var resourceKrankyBearTrapperRedPlaidPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearTrapperRedPlaid.png",
	StaticContent: resourceKrankyBearTrapperRedPlaidPngData,
}

//go:embed Resources/Images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

// Traditional theme images
//
//go:embed Resources/Images/traditional/PacMan.png
var resourceTraditionalPacManPngData []byte
var resourceTraditionalPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/traditional/PacMan.png",
	StaticContent: resourceTraditionalPacManPngData,
}

//go:embed Resources/Images/traditional/Blinky.png
var resourceTraditionalBlinkyPngData []byte
var resourceTraditionalBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/traditional/Blinky.png",
	StaticContent: resourceTraditionalBlinkyPngData,
}

//go:embed Resources/Images/traditional/Pinky.png
var resourceTraditionalPinkyPngData []byte
var resourceTraditionalPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/traditional/Pinky.png",
	StaticContent: resourceTraditionalPinkyPngData,
}

//go:embed Resources/Images/traditional/Inky.png
var resourceTraditionalInkyPngData []byte
var resourceTraditionalInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/traditional/Inky.png",
	StaticContent: resourceTraditionalInkyPngData,
}

//go:embed Resources/Images/traditional/Clyde.png
var resourceTraditionalClydePngData []byte
var resourceTraditionalClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/traditional/Clyde.png",
	StaticContent: resourceTraditionalClydePngData,
}

// Camo theme images
//
//go:embed Resources/Images/camo/PacManBrushStroke.png
var resourceCamoPacManPngData []byte
var resourceCamoPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/camo/PacManBrushStroke.png",
	StaticContent: resourceCamoPacManPngData,
}

//go:embed Resources/Images/camo/BlinkyRealTree.png
var resourceCamoBlinkyPngData []byte
var resourceCamoBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/camo/BlinkyRealTree.png",
	StaticContent: resourceCamoBlinkyPngData,
}

//go:embed Resources/Images/camo/PinkyMossyOak.png
var resourceCamoPinkyPngData []byte
var resourceCamoPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/camo/PinkyMossyOak.png",
	StaticContent: resourceCamoPinkyPngData,
}

//go:embed Resources/Images/camo/InkyWoodland.png
var resourceCamoInkyPngData []byte
var resourceCamoInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/camo/InkyWoodland.png",
	StaticContent: resourceCamoInkyPngData,
}

//go:embed Resources/Images/camo/ClydeChocChip.png
var resourceCamoClydePngData []byte
var resourceCamoClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/camo/ClydeChocChip.png",
	StaticContent: resourceCamoClydePngData,
}

// Animal theme images
//
//go:embed Resources/Images/animal/PacMan.png
var resourceAnimalPacManPngData []byte
var resourceAnimalPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/animal/PacMan.png",
	StaticContent: resourceAnimalPacManPngData,
}

//go:embed Resources/Images/animal/BlinkyBear.png
var resourceAnimalBlinkyPngData []byte
var resourceAnimalBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/animal/BlinkyBear.png",
	StaticContent: resourceAnimalBlinkyPngData,
}

//go:embed Resources/Images/animal/PinkyLion.png
var resourceAnimalPinkyPngData []byte
var resourceAnimalPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/animal/PinkyLion.png",
	StaticContent: resourceAnimalPinkyPngData,
}

//go:embed Resources/Images/animal/InkyBaboon.png
var resourceAnimalInkyPngData []byte
var resourceAnimalInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/animal/InkyBaboon.png",
	StaticContent: resourceAnimalInkyPngData,
}

//go:embed Resources/Images/animal/ClydeMoose.png
var resourceAnimalClydePngData []byte
var resourceAnimalClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/animal/ClydeMoose.png",
	StaticContent: resourceAnimalClydePngData,
}

// Football theme images
//
//go:embed Resources/Images/football/PacManReferee.png
var resourceFootballPacManPngData []byte
var resourceFootballPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/football/PacManReferee.png",
	StaticContent: resourceFootballPacManPngData,
}

//go:embed Resources/Images/football/BlinkyDallasCowboy.png
var resourceFootballBlinkyPngData []byte
var resourceFootballBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/football/BlinkyDallasCowboy.png",
	StaticContent: resourceFootballBlinkyPngData,
}

//go:embed Resources/Images/football/PinkyNEPatriot.png
var resourceFootballPinkyPngData []byte
var resourceFootballPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/football/PinkyNEPatriot.png",
	StaticContent: resourceFootballPinkyPngData,
}

//go:embed Resources/Images/football/InkyPhillyEagle.png
var resourceFootballInkyPngData []byte
var resourceFootballInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/football/InkyPhillyEagle.png",
	StaticContent: resourceFootballInkyPngData,
}

//go:embed Resources/Images/football/ClydeVegasRaider.png
var resourceFootballClydePngData []byte
var resourceFootballClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/football/ClydeVegasRaider.png",
	StaticContent: resourceFootballClydePngData,
}

// Hogwarts theme images
//
//go:embed Resources/Images/hogwarts/PacManSortingHat.png
var resourceHogwartsPacManPngData []byte
var resourceHogwartsPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts/PacManSortingHat.png",
	StaticContent: resourceHogwartsPacManPngData,
}

//go:embed Resources/Images/hogwarts/BlinkyGriffindor.png
var resourceHogwartsBlinkyPngData []byte
var resourceHogwartsBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts/BlinkyGriffindor.png",
	StaticContent: resourceHogwartsBlinkyPngData,
}

//go:embed Resources/Images/hogwarts/PinkyHufflepuff.png
var resourceHogwartsPinkyPngData []byte
var resourceHogwartsPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts/PinkyHufflepuff.png",
	StaticContent: resourceHogwartsPinkyPngData,
}

//go:embed Resources/Images/hogwarts/InkyRavenclaw.png
var resourceHogwartsInkyPngData []byte
var resourceHogwartsInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts/InkyRavenclaw.png",
	StaticContent: resourceHogwartsInkyPngData,
}

//go:embed Resources/Images/hogwarts/ClydeSlytherin.png
var resourceHogwartsClydePngData []byte
var resourceHogwartsClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts/ClydeSlytherin.png",
	StaticContent: resourceHogwartsClydePngData,
}

// College Football theme images
//
//go:embed Resources/Images/collegefootball/PacManRefereee.png
var resourceCollegeFootballPacManPngData []byte
var resourceCollegeFootballPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/collegefootball/PacManRefereee.png",
	StaticContent: resourceCollegeFootballPacManPngData,
}

//go:embed Resources/Images/collegefootball/BlinkyOhioState.png
var resourceCollegeFootballBlinkyPngData []byte
var resourceCollegeFootballBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/collegefootball/BlinkyOhioState.png",
	StaticContent: resourceCollegeFootballBlinkyPngData,
}

//go:embed Resources/Images/collegefootball/PinkyMichiganWolverine.png
var resourceCollegeFootballPinkyPngData []byte
var resourceCollegeFootballPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/collegefootball/PinkyMichiganWolverine.png",
	StaticContent: resourceCollegeFootballPinkyPngData,
}

//go:embed Resources/Images/collegefootball/InkyTexasLonghorn.png
var resourceCollegeFootballInkyPngData []byte
var resourceCollegeFootballInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/collegefootball/InkyTexasLonghorn.png",
	StaticContent: resourceCollegeFootballInkyPngData,
}

//go:embed Resources/Images/collegefootball/ClydeNotreDame.png
var resourceCollegeFootballClydePngData []byte
var resourceCollegeFootballClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/collegefootball/ClydeNotreDame.png",
	StaticContent: resourceCollegeFootballClydePngData,
}

// Hogwarts2 theme images
//
//go:embed Resources/Images/hogwarts2/PacManSortingHat.png
var resourceHogwarts2PacManPngData []byte
var resourceHogwarts2PacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts2/PacManSortingHat.png",
	StaticContent: resourceHogwarts2PacManPngData,
}

//go:embed Resources/Images/hogwarts2/BlinkyGriffindor.png
var resourceHogwarts2BlinkyPngData []byte
var resourceHogwarts2BlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts2/BlinkyGriffindor.png",
	StaticContent: resourceHogwarts2BlinkyPngData,
}

//go:embed Resources/Images/hogwarts2/PinkyHufflePuff.png
var resourceHogwarts2PinkyPngData []byte
var resourceHogwarts2PinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts2/PinkyHufflePuff.png",
	StaticContent: resourceHogwarts2PinkyPngData,
}

//go:embed Resources/Images/hogwarts2/InkyRavenclaw.png
var resourceHogwarts2InkyPngData []byte
var resourceHogwarts2InkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts2/InkyRavenclaw.png",
	StaticContent: resourceHogwarts2InkyPngData,
}

//go:embed Resources/Images/hogwarts2/ClydeSlytherin.png
var resourceHogwarts2ClydePngData []byte
var resourceHogwarts2ClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/hogwarts2/ClydeSlytherin.png",
	StaticContent: resourceHogwarts2ClydePngData,
}

// Superheroes theme images
//
//go:embed Resources/Images/superheroes/PacManRocket.png
var resourceSuperheroesPacManPngData []byte
var resourceSuperheroesPacManPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/superheroes/PacManRocket.png",
	StaticContent: resourceSuperheroesPacManPngData,
}

//go:embed Resources/Images/superheroes/Blinky.png
var resourceSuperheroesBlinkyPngData []byte
var resourceSuperheroesBlinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/superheroes/Blinky.png",
	StaticContent: resourceSuperheroesBlinkyPngData,
}

//go:embed Resources/Images/superheroes/Pinky.png
var resourceSuperheroesPinkyPngData []byte
var resourceSuperheroesPinkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/superheroes/Pinky.png",
	StaticContent: resourceSuperheroesPinkyPngData,
}

//go:embed Resources/Images/superheroes/Inky.png
var resourceSuperheroesInkyPngData []byte
var resourceSuperheroesInkyPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/superheroes/Inky.png",
	StaticContent: resourceSuperheroesInkyPngData,
}

//go:embed Resources/Images/superheroes/Clyde.png
var resourceSuperheroesClydePngData []byte
var resourceSuperheroesClydePng = &fyne.StaticResource{
	StaticName:    "Resources/Images/superheroes/Clyde.png",
	StaticContent: resourceSuperheroesClydePngData,
}
